apiVersion: view.open-cluster-management.io/v1beta1
kind: ManagedClusterView
metadata:
  name: <CR name>
  namespace: <namespace of managed cluster>
spec:
  scope:
    kind: ConfigMap
    version: v1
    name: default-ingress-cert
    namespace: openshift-config-managed
