apiVersion: action.open-cluster-management.io/v1beta1
kind: ManagedClusterAction
spec:
  actionType: Create
  kube:
    resource: OAuthClient
    template:
      apiVersion: oauth.openshift.io/v1
      kind: OAuthClient
      grantMethod: auto
