apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    include.release.openshift.io/single-node-production-edge: "true"
  name: redhat-helm-repo
spec:
  name: Red Hat Helm Charts
  connectionConfig:
    url: https://redhat-developer.github.io/redhat-helm-charts
