apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: console
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    include.release.openshift.io/single-node-production-edge: "true"
grantMethod: auto
respondWithChallenges: false
