kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-console
rules:
# TODO: delete is needed for ownerRefs on older clusters
# should remove in the future.
- apiGroups:
  - console.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
