# Expose operator metrics
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
    service.beta.openshift.io/serving-cert-secret-name: serving-cert
  labels:
    name: console-operator
  name: metrics
  namespace: openshift-console-operator
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    name: console-operator
  sessionAffinity: None
  type: ClusterIP
---
# conversion webhook server service
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
    service.beta.openshift.io/serving-cert-secret-name: webhook-serving-cert
  labels:
    name: console-conversion-webhook
  name: webhook
  namespace: openshift-console-operator
spec:
  ports:
    - name: webhook
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    name: console-conversion-webhook
  sessionAffinity: None
  type: ClusterIP
