apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: helm-download-links
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  description: |
    Helm 4 is a package manager for Kubernetes. You can use it to
    define, install, and upgrade applications packaged as Helm Charts.
  displayName: helm - Helm 4 CLI
  links:
    - href: 'https://mirror.openshift.com/pub/cgw/helm/4.2.3'
      text: Download Helm v4
---
apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: helm3-download-links
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  description: |
    Helm 3 is a package manager for Kubernetes. You can use it to
    define, install, and upgrade applications packaged as Helm Charts.
    Helm 3 is still available for operational continuity, but it will
    not be compatible with future releases of OpenShift Container
    Platform (OCP). Upgrade to Helm 4 for continued compatibility with
    future OCP releases.
  displayName: helm - Helm 3 CLI
  links:
    - href: 'https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest'
      text: Download Helm v3
