apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: openshift-blog
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/single-node-production-edge: "true"
spec:
  href: 'https://blog.openshift.com'
  location: HelpMenu
  text: OpenShift Blog
