apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: enable-developer-perspective
spec:
  accessReviewResources:
    - group: operator.openshift.io
      resource: consoles
      verb: patch
    - group: operator.openshift.io
      resource: consoles
      verb: update
  conclusion: You have learned how to enable and disable the Developer perspective!
  description: Learn how to enable and disable the Developer perspective.
  displayName: Enable the Developer Perspective
  durationMinutes: 5
  introduction: 'This guide walks you through enabling the Developer perspective in OpenShift. You will learn how to modify console setting via the web interface or the CLI, allowing developers to access a streamlined, developer-friendly view within the OpenShift web console.'
  prerequisites:
    - You must have cluster administrator or appropriate RBAC permissions to modify console settings.
  tags:
    - developer
    - perspective
    - ODC
  tasks:
    - description: |-
        **Search page**
        1. Open the **Home** section in the side navigation, and navigate to the **Search** page
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          To verify that you are in the right place:
          1. You should see a search bar and a Resource filter dropdown at the top of the page.
      summary:
        failed: Try the steps again.
        success: Great work!
      title: Navigate to the search page
    - description: |-
        **Search results**
        1. Under the **Resource** filter dropdown, search for **operator.openshift.io/v1**
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          To verify that you have the right access:
          1. You should see a list of results, including Console Operator.
      summary:
        failed: Try the steps again.
        success: Great work!
      title: Locate the Console Operator Resource
    - description: |-
        **Cluster details**
        1. Click on the **Console Operator** resource to open the cluster details page.
        2. Click on the **Actions menu** and select **Customize**.

          a. This will open the Cluster Configuration page
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          To verify that you have the right place:
          1. You should see details related to the Console Operator, including configurations and status.
          2. The Cluster Configuration page should open, showing different customization options.
      summary:
        failed: Try the steps again.
        success: Great work!
      title: Customize cluster configuration
    - description: |-
        ### Using the UI 
        1. In the **General** tab, locate the **Perspectives** section. 
        2. Enable or disable the Developer perspective as needed. Changes are automatically applied. 
        ### Using the CLI 
        1. To enable the Developer perspective using the CLI, run the following command: 
            
        `oc patch console.operator.openshift.io/cluster --type='merge' -p '{"spec":{"customization":{"perspectives":[{"id":"dev","visibility":{"state":"Enabled"}}]}}}'`{{execute}}
        ### Note
        - It will take some time to reflect in the UI as the console pod gets restarted. And reload the console is required.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          To verify that you have the right place:
          1. You should see details related to the Console Operator, including configurations and status.
          2. The Cluster Configuration page should open, showing different customization options.
      summary:
        failed: Try the steps again.
        success: Great work!
      title: Enable the Developer Perspective
