apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: install-secrets-store-csi
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  accessReviewResources:
    - group: operators.coreos.com
      resource: operatorgroups
      verb: list
    - group: packages.operators.coreos.com
      resource: packagemanifests
      verb: list
  displayName: Install the Secrets Store CSI Driver Operator
  durationMinutes: 10
  description: >-
    Install the Secrets Store CSI Driver Operator to mount secrets from external
    stores as volumes in your pods.
  tags:
    - storage
    - security
    - secrets
    - csi
  introduction: |-
    ### In this quick start, you'll install the Secrets Store CSI Driver Operator to mount secrets from external sources as volumes.

    The Secrets Store CSI Driver Operator allows you to mount secrets, keys, and certificates from external secret
    management systems directly into your pods as volumes. This is accomplished using a CSI (Container Storage Interface)
    volume, which enables the Kubelet to retrieve the secrets directly from external sources and mount them into the pod.

    ### Why use Secrets Store CSI Driver?

    - **Volume Mounting**: Mount secrets directly as files in your pod's filesystem
    - **Provider Integration**: Works with HashiCorp Vault, Azure Key Vault, AWS Secrets Manager, GCP Secret Manager, and more
    - **Ephemeral Volumes**: Secrets are only accessible to the pod and are removed when the pod is deleted
    - **Sync to Kubernetes Secrets**: Optionally sync mounted secrets to Kubernetes Secret objects
    - **Rotation**: Secrets can be automatically updated when they change in the external system

    ### How it works

    You define a **SecretProviderClass** that specifies how to connect to your external secrets manager and which
    secrets to retrieve. Then, you reference this SecretProviderClass in your pod's volume definition. When the pod
    starts, the CSI driver retrieves the secrets and mounts them into the pod.
  tasks:
    - title: Install the Secrets Store CSI Driver Operator
      description: |-
        ### To install the Secrets Store CSI Driver Operator:

        1. Go to the **Software Catalog** from the [Ecosystem]{{highlight qs-nav-ecosystem}} section of the navigation.

        2. In the **Filter by keyword** field, type `Secrets Store CSI`.

        3. Look for **Secrets Store CSI Driver Operator**. If the tile has an **Installed** label on it, the Operator is already installed. Proceed to next task.

        4. Click the tile to open the side panel.

        5. At the top of the side panel, click **Install**.

        6. On the Install Operator page, ensure the **Update Channel** is set to the latest stable version.

        7. Click **Install** to begin the installation process. The operator will be installed in the **openshift-cluster-csi-drivers** namespace.

        8. Wait for the Secrets Store CSI Driver Operator's status to change from **Installing operator** to **Operator installed - Ready for use**.
      review:
        instructions: |-
          #### Verify the Secrets Store CSI Driver Operator was successfully installed:

          1. Navigate to **Ecosystem** → **Installed Operators** from the [Ecosystem]{{highlight qs-nav-ecosystem}} section.

          2. Look for **Secrets Store CSI Driver Operator** in the list.

          3. In the Status column, is the Secrets Store CSI Driver Operator's status **Succeeded**?

          To verify the operator pod is running:

          1. Navigate to **Workloads** → **Pods** from the [Workloads]{{highlight qs-nav-workloads}} section.

          2. In the **Project** dropdown menu at the top, select **openshift-cluster-csi-drivers**.

          3. Verify that the **secrets-store-csi-driver-operator** pod is in **Running** status.
        failedTaskHelp: >-
          This task isn't verified yet. Try the task again, or [read
          more](https://docs.openshift.com/container-platform/latest/storage/container_storage_interface/persistent-storage-csi-secrets-store.html)
          about installing the Secrets Store CSI Driver Operator.
      summary:
        success: >-
          You just installed the Secrets Store CSI Driver Operator! Next, we'll
          deploy the ClusterCSIDriver to activate the CSI driver.
        failed: >-
          This task is incomplete. Try the task again, or read more about this
          topic.
    - title: Deploy the ClusterCSIDriver custom resource
      description: |-
        ### What is ClusterCSIDriver?

        The ClusterCSIDriver custom resource instructs the operator to deploy and manage the Secrets Store CSI driver
        on your cluster. Once deployed, the CSI driver will run as a DaemonSet on all nodes, ready to mount secrets
        from external sources into your pods.

        ### To deploy the ClusterCSIDriver custom resource:

        1. Navigate to **CustomResourceDefinitions** from the [Administration]{{highlight qs-nav-administration}} section.

        2. In the **Search by name** field, type `ClusterCSIDriver`.

        3. Click on the **ClusterCSIDriver** custom resource definition from the list.

        4. Click on the **Instances** tab.

        5. Click **Create ClusterCSIDriver** button.

        6. In the YAML editor, use the following configuration:

        ```yaml
        apiVersion: operator.openshift.io/v1
        kind: ClusterCSIDriver
        metadata:
          name: secrets-store.csi.k8s.io
        spec:
          managementState: Managed
        ```

        7. Click **Create** to deploy the ClusterCSIDriver.

        8. Wait for the CSI driver pods to be deployed across your cluster nodes.
      review:
        instructions: |-
          #### Verify the ClusterCSIDriver was successfully deployed:

          1. Navigate to **Workloads** → **DaemonSets** from the [Workloads]{{highlight qs-nav-workloads}} section.

          2. In the **Project** dropdown menu at the top, select **openshift-cluster-csi-drivers**.

          3. Look for **csi-secrets-store** and **csi-secrets-store-node** DaemonSets.

          4. Verify that the desired number of pods matches the current number of pods for each DaemonSet.

          Are all CSI driver pods running successfully?
        failedTaskHelp: >-
          This task isn't verified yet. Try the task again. Check the operator
          logs if the CSI driver pods are not deploying correctly.
      summary:
        success: >-
          You have successfully deployed the Secrets Store CSI Driver! You can
          now create SecretProviderClass resources and mount secrets from external
          sources as volumes in your pods.
        failed: >-
          This task is incomplete. Check your work to make sure the ClusterCSIDriver
          was created correctly.
  conclusion: >-
    Your Secrets Store CSI Driver is ready! You can now create SecretProviderClass
    resources to define connections to external secret management systems and mount
    secrets as volumes in your workloads. To learn more, refer to the
    [OpenShift documentation](https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/nodes/working-with-pods#nodes-pods-secrets-store).
  nextQuickStart: []
