apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: install-external-secrets-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  accessReviewResources:
    - group: operators.coreos.com
      resource: operatorgroups
      verb: list
    - group: packages.operators.coreos.com
      resource: packagemanifests
      verb: list
  displayName: Install the External Secrets Operator for Red Hat OpenShift
  durationMinutes: 10
  description: >-
    Install the External Secrets Operator for Red Hat OpenShift to synchronize secrets from external
    secret management systems into OpenShift.
  tags:
    - security
    - secrets
    - vault
    - integration
  introduction: |-
    ### In this quick start, you'll install the External Secrets Operator for Red Hat OpenShift to manage secrets from external sources.

    The External Secrets Operator for Red Hat OpenShift is a OpenShift operator that integrates external secret management systems like
    HashiCorp Vault, AWS Secrets Manager, Azure Key Vault, Google Secret Manager and more.
    It reads information from external APIs and automatically injects the values into a Kubernetes Secret.


    ### Usage

    You can use a **SecretStore** or **ClusterSecretStore** to define how to connect to your external secrets manager,
    and use an **ExternalSecret** resource to define which secrets to pull and where to place them in your OpenShift cluster.
  tasks:
    - title: Install the External Secrets Operator for Red Hat OpenShift
      description: |-
        ### To install the External Secrets Operator:

        1. Go to the **Software Catalog** from the [Ecosystem]{{highlight qs-nav-ecosystem}} section of the navigation.

        2. In the **Filter by keyword** field, type `External Secrets`.

        3. Look for **External Secrets Operator for Red Hat OpenShift**. If the tile has an **Installed** label on it, the Operator is already installed. Proceed to task two.

        4. Click the tile to open the side panel.

        5. At the top of the side panel, click **Install**.

        6. On the Install Operator page, ensure the **Update Channel** is set to the latest stable version.

        7. Select the installation mode and namespace. The default **All namespaces on the cluster** is recommended.

        8. Click **Install** to begin the installation process.

        9. Wait for the External Secrets Operator for Red Hat OpenShift's status to change from **Installing operator** to **Operator installed - Ready for use**.
      review:
        instructions: |-
          #### Verify the External Secrets Operator was successfully installed:

          1. Navigate to **Ecosystem** → **Installed Operators** from the [Ecosystem]{{highlight qs-nav-ecosystem}} section.

          2. Look for **External Secrets Operator for Red Hat OpenShift** in the list.

          3. In the Status column, is the External Secrets Operator for Red Hat OpenShift's status **Succeeded**?
        failedTaskHelp: >-
          This task isn't verified yet. Try the task again, or [read
          more](https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/security_and_compliance/external-secrets-operator-for-red-hat-openshift)
          about installing the External Secrets Operator.
      summary:
        success: >-
          You just installed the External Secrets Operator for Red Hat OpenShift! Next, we'll deploy
          the ExternalSecretsConfig to activate the operator components.
        failed: >-
          This task is incomplete. Try the task again, or read more about this
          topic.
    - title: Deploy the ExternalSecretsConfig custom resource
      description: |-
        ### What is ExternalSecretsConfig?

        Installing the External Secrets Operator for Red Hat OpenShift provides you with the necessary APIs to deploy the ExternalSecrets operand.
        When an ExternalSecretsConfig CR is deployed, a new Deployment is created that manages the external-secrets singleton and
        keeps it in the desired state.

        ### To deploy the ExternalSecretsConfig custom resource:

        1. Navigate to **Ecosystem** → **Installed Operators** from the [Ecosystem]{{highlight qs-nav-ecosystem}} section.

        2. Click on **External Secrets Operator for Red Hat OpenShift** from the list.

        3. Find the **ExternalSecretsConfig** custom resource in the **Provided APIs** list or in the top side-scrolling menu bar.
           - From the list of **Provided APIs** click the **Create instance** link
           - From the **top side-scrolling menu bar** click **ExternalSecretsConfig** and then click **Create ExternalSecretsConfig**

        4. For this quick start, you can use the default configurations for the ExternalSecretsConfig deployment, including an allow-all egress policy.
           - **Note**: An allow-all egress policy is not recommended in production environments.

        5. Copy the below manifest into the console editor for the ExternalSecretsConfig deployment:

        ```yaml
        spec:
          controllerConfig:
            networkPolicies:
              - name: allow-external-secrets-egress
                componentName: ExternalSecretsCoreController
                egress:
                - {}
        ```

        6. Click **Create** to deploy the ExternalSecretsConfig.

        7. Wait for the controller pods to start running.
      review:
        instructions: |-
          #### Verify the ExternalSecretsConfig was successfully deployed:

          1. Navigate to **Workloads** → **Pods** from the [Workloads]{{highlight qs-nav-workloads}} section.

          2. In the **Project** dropdown menu at the top, select **external-secrets**.

          3. Verify that the following pods are in **Running** status:
             - external-secrets
             - external-secrets-cert-controller
             - external-secrets-webhook

          Do all pods show a **Running** status?
        failedTaskHelp: >-
          This task isn't verified yet. Try the task again. If the pods are not
          running, check the operator logs for more details.
      summary:
        success: >-
          You have completely deployed the External Secrets Operator for Red Hat OpenShift! You can
          now create SecretStores and ExternalSecrets to synchronize secrets
          from external sources. Check out the next quick start for a simple
          example of how to use the Custom Resources provided by the operator.
        failed: >-
          This task is incomplete. Check your work to make sure the ExternalSecretsConfig
          was created correctly.
  conclusion: >-
    Your External Secrets Operator for Red Hat OpenShift is ready! You can now configure connections
    to external secret management systems and start synchronizing secrets into
    your OpenShift cluster. To learn more about using the External Secrets Operator,
    refer to the [OpenShift documentation](https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/security_and_compliance/external-secrets-operator-for-red-hat-openshift).
  nextQuickStart: []
