apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: janus-idp-installation-via-helm
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  displayName: Install Janus IDP with a Helm Chart
  description: Install and configure a Janus Internal Developer Portal (IDP) instance, build on Backstage, on your cluster.
  durationMinutes: 10
  tags:
    - janus
    - backstage
    - idp
    - developer-portal
    - helm
  icon: |-
    data:image/svg+xml;base64,
    PHN2ZyB3aWR0aD0iMzM1IiBoZWlnaHQ9IjM0MCIgdmlld0JveD0iMCAwIDMzNSAzNDAiIGZpbGw9
    Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPGcgY2xpcC1wYXRo
    PSJ1cmwoI2NsaXAwXzFfMTEpIj4KICAgIDxwYXRoCiAgICAgIGQ9Ik0zMzQuNjY5IDE1MC45NzNW
    MTY1LjU0OEMzMjEuNTgzIDE2NS41NDggMzEyLjQxNCAxNjguMjkxIDMwNy4xNjQgMTczLjc3NkMz
    MDEuOTkyIDE3OS4yNjIgMjk5LjQwNiAxODguNDMgMjk5LjQwNiAyMDEuMjgxVjIzOC44OTVDMjk5
    LjQwNiAyNDkuNzA5IDI5OC4zNDggMjU5LjA3MyAyOTYuMjMzIDI2Ni45ODhDMjk0LjE5NSAyNzQu
    OTAyIDI5MC44MjYgMjgxLjQ0NSAyODYuMTI0IDI4Ni42MTdDMjgxLjQyMiAyOTEuNzg5IDI3NS4x
    NTMgMjk1LjYyOSAyNjcuMzE3IDI5OC4xMzZDMjU5LjQ4MSAzMDAuNjQ0IDI0OS44MDMgMzAxLjg5
    OCAyMzguMjg0IDMwMS44OThWMjc4Ljg1OUMyNDcuMzc0IDI3OC44NTkgMjU0LjUwNSAyNzcuNDEg
    MjU5LjY3NyAyNzQuNTFDMjY0LjkyNyAyNzEuNjg5IDI2OC42MSAyNjcuMzQgMjcwLjcyNiAyNjEu
    NDYzQzI3Mi45MiAyNTUuNTg2IDI3NC4wMTcgMjQ4LjA2MyAyNzQuMDE3IDIzOC44OTVWMTkxLjg3
    OEMyNzQuMDE3IDE4NS43NjYgMjc0LjgwMSAxODAuMjAyIDI3Ni4zNjggMTc1LjE4N0MyNzguMDEz
    IDE3MC4xNzIgMjgwLjk5MSAxNjUuODYyIDI4NS4zMDEgMTYyLjI1N0MyODkuNjExIDE1OC42NTIg
    Mjk1LjcyMyAxNTUuODcxIDMwMy42MzggMTUzLjkxMkMzMTEuNjMxIDE1MS45NTMgMzIxLjk3NCAx
    NTAuOTczIDMzNC42NjkgMTUwLjk3M1pNMjM4LjI4NCAwLjk4ODYyQzI0OS44MDMgMC45ODg2MiAy
    NTkuNDgxIDIuMjQyNDEgMjY3LjMxNyA0Ljc1QzI3NS4xNTMgNy4yNTc1NyAyODEuNDIyIDExLjA5
    NzMgMjg2LjEyNCAxNi4yNjkyQzI5MC44MjYgMjEuNDQxIDI5NC4xOTUgMjcuOTg0MiAyOTYuMjMz
    IDM1Ljg5ODhDMjk4LjM0OCA0My44MTMzIDI5OS40MDYgNTMuMTc3NSAyOTkuNDA2IDYzLjk5MTVW
    MTAxLjYwNUMyOTkuNDA2IDExNC40NTYgMzAxLjk5MiAxMjMuNjI1IDMwNy4xNjQgMTI5LjExQzMx
    Mi40MTQgMTM0LjU5NSAzMjEuNTgzIDEzNy4zMzggMzM0LjY2OSAxMzcuMzM4VjE1MS45MTNDMzIx
    Ljk3NCAxNTEuOTEzIDMxMS42MzEgMTUwLjkzNCAzMDMuNjM4IDE0OC45NzVDMjk1LjcyMyAxNDcu
    MDE2IDI4OS42MTEgMTQ0LjIzNCAyODUuMzAxIDE0MC42MjlDMjgwLjk5MSAxMzcuMDI1IDI3OC4w
    MTMgMTMyLjcxNSAyNzYuMzY4IDEyNy43QzI3NC44MDEgMTIyLjY4NCAyNzQuMDE3IDExNy4xMjEg
    Mjc0LjAxNyAxMTEuMDA5VjYzLjk5MTVDMjc0LjAxNyA1NC44MjMxIDI3Mi45MiA0Ny4zMDA0IDI3
    MC43MjYgNDEuNDIzM0MyNjguNjEgMzUuNDY3OCAyNjQuOTI3IDMxLjA3OTUgMjU5LjY3NyAyOC4y
    NTg1QzI1NC41MDUgMjUuNDM3NSAyNDcuMzc0IDI0LjAyNyAyMzguMjg0IDI0LjAyN1YwLjk4ODYy
    Wk0zMzQuNjY5IDEzNy4zMzhWMTY1LjU0OEgzMDYuOTI5VjEzNy4zMzhIMzM0LjY2OVoiCiAgICAg
    IGZpbGw9IiMwMDk1OTYiIC8+CiAgICA8cGF0aAogICAgICBkPSJNMC43NTE4MTggMTg4LjcyNUww
    Ljc5ODY0NSAxNzQuMTVDMTMuODg1IDE3NC4xOTIgMjMuMDYyMSAxNzEuNDc5IDI4LjMyOTkgMTY2
    LjAxMUMzMy41MTk0IDE2MC41NDIgMzYuMTM0OCAxNTEuMzgyIDM2LjE3NjEgMTM4LjUzMUwzNi4y
    OTY5IDEwMC45MTdDMzYuMzMxNiA5MC4xMDM0IDM3LjQxOTYgODAuNzQyNyAzOS41NjA4IDcyLjgz
    NUM0MS42MjM2IDY0LjkyNyA0NS4wMTQyIDU4LjM5NDcgNDkuNzMyNSA1My4yMzc5QzU0LjQ1MDgg
    NDguMDgxMiA2MC43MzIgNDQuMjYxNiA2OC41NzYyIDQxLjc3OTJDNzYuNDIwNCAzOS4yOTY4IDg2
    LjEwMiAzOC4wNzQyIDk3LjYyMTIgMzguMTExMkw5Ny41NDcxIDYxLjE0OTRDODguNDU3MiA2MS4x
    MjAyIDgxLjMyMTcgNjIuNTQ3IDc2LjE0MDUgNjUuNDI5N0M3MC44ODEyIDY4LjIzMzkgNjcuMTg0
    MyA3Mi41NzExIDY1LjA0OTcgNzguNDQxNEM2Mi44MzY3IDg0LjMxMTQgNjEuNzE1NCA5MS44MzA2
    IDYxLjY4NiAxMDAuOTk5TDYxLjUzNDkgMTQ4LjAxNkM2MS41MTUzIDE1NC4xMjggNjAuNzEzOCAx
    NTkuNjg5IDU5LjEzMDQgMTY0LjY5OUM1Ny40Njg3IDE2OS43MDkgNTQuNDc3MiAxNzQuMDA5IDUw
    LjE1NTcgMTc3LjZDNDUuODM0MyAxODEuMTkxIDM5LjcxMzEgMTgzLjk1MyAzMS43OTIzIDE4NS44
    ODdDMjMuNzkzMiAxODcuODIgMTMuNDQ2NCAxODguNzY2IDAuNzUxODE4IDE4OC43MjVaTTk2LjY1
    NDQgMzM5LjAxOUM4NS4xMzUzIDMzOC45ODIgNzUuNDYxNyAzMzcuNjk3IDY3LjYzMzYgMzM1LjE2
    NEM1OS44MDU1IDMzMi42MzEgNTMuNTQ5IDMyOC43NzIgNDguODYzOSAzMjMuNTg1QzQ0LjE3ODgg
    MzE4LjM5OCA0MC44MzAzIDMxMS44NDQgMzguODE4MyAzMDMuOTIzQzM2LjcyOCAyOTYuMDAxIDM1
    LjcwMDIgMjg2LjYzNCAzNS43MzUgMjc1LjgyTDM1Ljg1NTggMjM4LjIwNkMzNS44OTcxIDIyNS4z
    NTUgMzMuMzQwNiAyMTYuMTc5IDI4LjE4NjQgMjEwLjY3N0MyMi45NTM4IDIwNS4xNzQgMTMuNzk0
    NCAyMDIuNDAyIDAuNzA4MDEyIDIwMi4zNkwwLjc1NDgzOSAxODcuNzg1QzEzLjQ0OTQgMTg3Ljgy
    NiAyMy43ODk5IDE4OC44MzkgMzEuNzc2NSAxOTAuODIzQzM5LjY4NDcgMTkyLjgwOCA0NS43ODc5
    IDE5NS42MDkgNTAuMDg2MiAxOTkuMjI4QzU0LjM4NDUgMjAyLjg0NiA1Ny4zNDg0IDIwNy4xNjYg
    NTguOTc3OSAyMTIuMTg2QzYwLjUyOSAyMTcuMjA2IDYxLjI5NDcgMjIyLjc3MiA2MS4yNzUxIDIy
    OC44ODVMNjEuMTI0IDI3NS45MDFDNjEuMDk0NiAyODUuMDcgNjIuMTY3NSAyOTIuNTk2IDY0LjM0
    MjcgMjk4LjQ4QzY2LjQzOTMgMzA0LjQ0MiA3MC4xMDgyIDMwOC44NDIgNzUuMzQ5NCAzMTEuNjhD
    ODAuNTEyMSAzMTQuNTE4IDg3LjYzODUgMzE1Ljk1MSA5Ni43Mjg0IDMxNS45OEw5Ni42NTQ0IDMz
    OS4wMTlaTTAuNzA4MDEyIDIwMi4zNkwwLjc5ODY0NSAxNzQuMTVMMjguNTM4NiAxNzQuMjM5TDI4
    LjQ0NzkgMjAyLjQ0OUwwLjcwODAxMiAyMDIuMzZaIgogICAgICBmaWxsPSIjMDA5NTk2IiAvPgog
    ICAgPHBhdGggZD0iTTk3IDg3VjI5MEgyNDEiIHN0cm9rZT0iIzAwOTU5NiIgc3Ryb2tlLXdpZHRo
    PSIyNCIgLz4KICAgIDxwYXRoIGQ9Ik0yMzguMjE0IDI1My40NjJMMjM4Ljg2NyA1MC40NjI3TDk0
    Ljg2NzMgNTAuMDAwMSIgc3Ryb2tlPSIjMDA5NTk2IiBzdHJva2Utd2lkdGg9IjI0IiAvPgogICAg
    PHBhdGggZD0iTTI0MC45NzcgMzI3LjQ3MUw4OC45NzczIDMyNi45ODMiIHN0cm9rZT0iIzAwOTU5
    NiIgc3Ryb2tlLXdpZHRoPSIyNCIgLz4KICA8L2c+CiAgPGRlZnM+CiAgICA8Y2xpcFBhdGggaWQ9
    ImNsaXAwXzFfMTEiPgogICAgICA8cmVjdCB3aWR0aD0iMzM1IiBoZWlnaHQ9IjM0MCIgZmlsbD0i
    d2hpdGUiIC8+CiAgICA8L2NsaXBQYXRoPgogIDwvZGVmcz4KPC9zdmc+
  introduction: |-
    **Janus IDP**, is a Red Hat sponsored community for building internal developer portals, built on the CNCF project Backstage.

    Janus IDP is a Backstage distribution with batteries included:

    * A **catalog** of all services, components, and more.
    * **Golden Path Templates** provide your developers with an easy way to set up new projects with best practices.
    * Preinstalled with **additional plugins**.
    * Your developer portal is **extendable with plugins** from Backstage.

    This **Janus IDP Helm Chart** has some additional features enabled by default:

    * It uses [janus-idp/backstage-showcase](https://github.com/janus-idp/backstage-showcase/) that pre-loads many useful plugins and features.
    * Automatically exposes a Route for easy access to the instance.
    * And an OpenShift-compatible PostgreSQL database storage.
  tasks:
    - title: Install Janus IDP with a Helm Chart
      description: |-
        To install Janus IDP via Helm:

        1. Click on the [perspective switcher]{{highlight qs-perspective-switcher}} at the top of the navigation and select Developer.
        2. In the navigation menu, click [Add]{{highlight qs-nav-add}} and then select **Helm Chart**.
        3. If needed, switch or create a new project from the **Project dropdown**.
        4. Search for **Backstage**
        5. Select the card **Backstage, Provided by Janus IDP**, and press **Create** to open a page to configure the Helm Chart.
        6. **Optional:** Change the default configuration via the form (click on Root Schema to expand the configuration) or YAML based on your needs.
           
           You can update the configuration later as well.
        7. Press **Create** to install the Janus IDP Helm Chart.
      review:
        instructions: |-
          #### To verify the application was successfully created:

          1. You should now see a Helm Chart “backstage” with a "backstage" Deployment in your [Topology]{{highlight qs-nav-topology}} view.
          2. After a few seconds, the Deployment should show a blue ring around the Janus IDP icon to indicate that the Janus IDP Pod is running.
          3. Click on the URL decorator in the top-right corner of the "backstage" Deployment to open your Janus IDP instance.
        failedTaskHelp: |-
          You can also click in the navigation menu on [Helm]{{highlight qs-nav-helm}} and check the Helm Release status. The status column should show "Deployed".
          
          Click on the Helm Chart and open the **Resources** tab to see if any Kubernetes resources are pending or to investigate underlying issues.
      summary:
        success: You have installed Janus IDP!
        failed: Try the steps again.
    - title: Know how to upgrade your Janus IDP installation
      description: |-
        The **Janus Community** maintains the **Janus IDP Helm Chart**, and will be updated regularly.

        But your installation will not update automatically. If you need automatic updates, you can install Janus IDP via an operator.

        To update your Janus IDP installation:

        1. Ensure you have a **backup** of your installation.
        2. In the navigation menu, click [Helm]{{highlight qs-nav-helm}}.
        3. Select your **backstage** Helm Release. You can see your current version under **Chart version**.
        4. Click the **Actions** menu button in the top right corner and select **Upgrade**.
        5. Switch to the **YAML view** and **save your current YAML configuration.**
        6. Select a new (or old) version from the **Chart version** dropdown. **A version change will reset your configuration** to the default values of that release.
        7. **Apply your YAML configuration.**
        8. Press **Upgrade**.
      review:
        instructions: |-
          #### To verify the application was successfully upgraded:

          1. Navigate back to [Helm]{{highlight qs-nav-helm}} and select your "backstage" Helm Release.
          2. Your Helm Chart should show "Deployed" again and an updated **Chart version**.
          3. The **Revision history** tab should show a new revision with the message "Upgrade complete".
        failedTaskHelp: |-
          Open the **Resources** tab to see if any Kubernetes resources are pending or to investigate underlying issues.
      summary:
        success: You have upgraded Janus IDP!
        failed: Try the steps again.
    - title: "Optional: Change the URL of your Janus IDP instance"
      description: |-
        To use a custom domain name, you must change some of **Helm Chart values**:

        1. In the navigation menu, click [Helm]{{highlight qs-nav-helm}}.
        2. Select your **backstage** Helm Release.
        3. Click the **Actions** menu button in the top right corner and select **Upgrade**.
        4. You can apply the following configuration with the Form view by clicking on **Root Schema > Global**
           or in the YAML view by applying as shown below:

           ```
        global:
          clusterRouterBase: janus-idp.example.com
          host: janus-idp.example.com
        ```{{copy}}
           <br/>

        5. **Optional:** For custom domain names, you might also need to configure TLS certificates.
           
           This could be configured under **Root Schema > OpenShift Route parameters > TLS**.

           Additional information can be found in the [Helm Chart README](https://github.com/janus-idp/helm-backstage/blob/main/charts/backstage/README.md).
        6. Press **Upgrade**.
      review:
        instructions: |-
          #### To verify the application was successfully updated:

          1. Navigate to [Topology]{{highlight qs-nav-topology}}
          2. Click on the URL decorator in the top-right corner of the "backstage" Deployment to open your Janus IDP instance.
          3. Verify that the correct URL is used and the Janus IDP installation works fine.
        failedTaskHelp: |-
          Doublecheck your Helm Chart hostname and TLS configuration, and if needed, the external DNS configuration.
      summary:
        success: You have upgraded Janus IDP!
        failed: Try the steps again.
    - title: "Optional: Add Janus IDP to the OpenShift Console Application menu"
      description: |-
        To add a new link to the application menu, you can create a `ConsoleLink` resource on your cluster.

        This resource is not created automatically because you can have multiple Janus IDP installations on one cluster.
        And this way, you can also link a single Janus IDP from multiple OpenShift clusters.

        1. Please copy the actual **Janus IDP URL** from [Topology]{{highlight qs-nav-topology}}, or open it in another browser tab.
        2. Click on the [Import YAML (plus icon)]{{highlight qs-masthead-import}} button at the top of the navigation.
        3. **Insert the YAML** below into the YAML editor, add your Janus IDP URL as `href`, and update the link `text` if needed.

            ```
            apiVersion: console.openshift.io/v1
        kind: ConsoleLink
        metadata:
          name: janus-idp-link
        spec:
          location: ApplicationMenu
          href: 
          text: Janus IDP
        ```{{copy}}

        3. Click **Create**.
      review:
        instructions: |-
          #### To verify that the application menu link is shown

          1. The [Application launcher]{{highlight qs-masthead-applications}} icon should be shown.
          2. Click on the Application launcher icon and check if your application menu item is shown.
          3. Verify that it opens your Janus IDP instance.
        failedTaskHelp: |-
          Doublecheck your `ConsoleLink` resource or try to reload the OpenShift Console.
      summary:
        success: You have upgraded Janus IDP!
        failed: Try the steps again.
  conclusion: |
    Your Janus IDP installation is deployed and ready.
