apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
  namespace: openshift-console-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: console-operator
  template:
    metadata:
      labels:
        name: console-operator
    spec:
      serviceAccountName: console-operator
      containers:
      - name: console-operator
        # for development
        # once you clone this repo, make changes, build & push a new image:
        # docker build quay.io/<your-user>/console-operator:latest .
        # docker push quay.io/<your-user>/console-operator:latest
        # then
        # oc apply -f examples/05-operator-alt-image.yaml
        # with this line updated:
        image: quay.io/<your-user>/console-operator:latest
        ports:
        - containerPort: 60000
          name: metrics
        command:
        - console
        - operator
        args:
        - "-v=4"
        - "--create-default-console=true"
        # 04-config.yaml provides this config for the operator
        - "--config=/var/run/configmaps/config/controller-config.yaml"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        env:
        - name: IMAGE
          value: docker.io/openshift/origin-console:latest
        - name: OPERATOR_NAME
          value: "console-operator"
      volumes:
      - name: config
        configMap:
          name: console-operator-config
