apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  namespace: openshift-cluster-version
  name: version
spec:
  overrides:
    - kind: Deployment
      name: console-operator
      namespace: openshift-console-operator
      unmanaged: true
      group: apps
    - kind: ClusterRole
      name: console-operator
      namespace: ""
      unmanaged: true
      group: rbac.authorization.k8s.io
