apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: console
  namespace: openshift-console
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: console
      component: ui