// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOperatorConfig) DeepCopyInto(out *ConsoleOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOperatorConfig.
func (in *ConsoleOperatorConfig) DeepCopy() *ConsoleOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(ConsoleOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsoleOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOperatorConfigList) DeepCopyInto(out *ConsoleOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConsoleOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOperatorConfigList.
func (in *ConsoleOperatorConfigList) DeepCopy() *ConsoleOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(ConsoleOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsoleOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOperatorConfigSpec) DeepCopyInto(out *ConsoleOperatorConfigSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	out.Customization = in.Customization
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOperatorConfigSpec.
func (in *ConsoleOperatorConfigSpec) DeepCopy() *ConsoleOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOperatorConfigStatus) DeepCopyInto(out *ConsoleOperatorConfigStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOperatorConfigStatus.
func (in *ConsoleOperatorConfigStatus) DeepCopy() *ConsoleOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConsoleOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Customization) DeepCopyInto(out *Customization) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Customization.
func (in *Customization) DeepCopy() *Customization {
	if in == nil {
		return nil
	}
	out := new(Customization)
	in.DeepCopyInto(out)
	return out
}
